# Generated by Django 3.1.2 on 2025-07-22 15:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('CRS', '0003_auto_20250722_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventEndDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 17, 44, 4, 19166, tzinfo=utc), verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventStartDate',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 22, 16, 44, 4, 19166, tzinfo=utc), verbose_name='start date'),
        ),
        migrations.AlterField(
            model_name='hdapplicant',
            name='hd_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc), verbose_name='HD Date Submitted'),
        ),
        migrations.AlterField(
            model_name='loaapplicant',
            name='LOA_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc), verbose_name='LOA Date Submitted'),
        ),
        migrations.AlterField(
            model_name='ojtapplicant',
            name='ojt_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc), verbose_name='OJT Date Submitted'),
        ),
        migrations.AlterField(
            model_name='outshifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='shifterapplicant',
            name='shifter_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc), verbose_name='Shifter Date Submitted'),
        ),
        migrations.AlterField(
            model_name='spapplicant',
            name='date',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='transfereeapplicant',
            name='transfer_dateSubmitted',
            field=models.DateField(default=datetime.datetime(2025, 7, 22, 15, 44, 4, 19166, tzinfo=utc), verbose_name='Tranfer Date Submitted'),
        ),
    ]
